// Auto-generated by rzp_sdk_upgrade_skill — negative-path crypto tests.
// Mirrors the shape of PR #133.
package utils

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"
)

func TestVerifyWebhookSignature_Valid(t *testing.T) {
	body := []byte("test body")
	secret := "test_secret"
	h := hmac.New(sha256.New, []byte(secret))
	h.Write(body)
	sig := hex.EncodeToString(h.Sum(nil))

	if !VerifySignature(body, sig, secret) {
		t.Error("expected valid signature to be accepted")
	}
}

func TestVerifyWebhookSignature_WrongLength(t *testing.T) {
	if VerifySignature([]byte("body"), "abc123", "secret") {
		t.Error("expected wrong-length signature to be rejected")
	}
}

func TestVerifyWebhookSignature_NonHex(t *testing.T) {
	if VerifySignature([]byte("body"), "not-valid-hex-chars!@#$", "secret") {
		t.Error("expected non-hex signature to be rejected")
	}
}

func TestVerifyWebhookSignature_Empty(t *testing.T) {
	if VerifySignature([]byte("body"), "", "secret") {
		t.Error("expected empty signature to be rejected")
	}
}

func TestVerifyWebhookSignature_TamperedValidHex(t *testing.T) {
	tampered := strings.Repeat("ab", 32)  // 64 hex chars = 32 bytes
	if VerifySignature([]byte("body"), tampered, "secret") {
		t.Error("expected tampered signature to be rejected")
	}
}

