name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.26'

      - name: Run coverage
        run: |
         cd resources
         go test -race -covermode=atomic -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
