# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
    # This workflow will build a golang project
    # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

    name: Go

    on:
      push:
        branches: [ "master" ]
      pull_request:
        branches: [ "master" ]

    jobs:

      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

        - name: Set up Go
          uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
          with:
            go-version: '1.20'

        - name: Build
          run: go build -v ./...

        - name: Test
          run: go test -v ./...
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
