name: Go
on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ 1.13, 1.14, 1.15, 1.16 ]

    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: |
          go get -v -t -d ./...
          go get -v golang.org/x/lint/golint

      - name: Run Tests
        run: go test -race --cover --covermode=atomic ./...

      - name: Lint Check
        run: golint -set_exit_status ./...
